#! /bin/sh


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Skype desktop='^9' follow=off state=tiled
bspc rule -a Steam desktop='^8' follow=off state=tiled

$HOME/.config/polybar/launch.sh
skypeforlinux &
steam &
betterlockscreen -u $HOME/Pictures/Wallpapers/ &
